application/orders/models.py
from application import db
from application.models import Base


assigned_developers = db.Table(
    "order_developers",
    Base.metadata,
    db.Column("order_id", db.Integer, db.ForeignKey("order.id")),
    db.Column("developer_id", db.Integer, db.ForeignKey("developer.id")),
)


class Order(Base):
    title = db.Column(db.String(100), nullable=False)
    requirements = db.Column(db.Text)
    complete = db.Column(db.Boolean, default=False, nullable=True)
    account_id = db.Column(db.Integer, db.ForeignKey("account.id"), nullable=True)
    # many-to-one rel to services
    service = db.relationship("Service", backref="order", lazy=True)
    service_id = db.Column(db.Integer, db.ForeignKey("service.id"), nullable=True)
    # many-to-many rel to developers
    developers = db.relationship(
        "Developer", secondary=assigned_developers, backref="orders", lazy="dynamic"
    )

    def __init__(self, title, requirements, account_id, service_id, complete):
        self.title = title
        self.requirements = requirements
        self.account_id = account_id
        self.service_id = service_id
        self.complete = complete

    def __repr__(self):
        return f"Order('{self.title}', '{self.requirements}', '{self.date_created}', '{self.date_modified}')"

application/orders/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    TextAreaField,
    SelectMultipleField,
    widgets,
)
from wtforms.validators import DataRequired, Length, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from application.services.models import Service
from application.developers.models import Developer


def service_query():
    return Service.query.filter().order_by(Service.name)


class MultiCheckboxField(SelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class OrderForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=3, max=30)])
    requirements = TextAreaField(
        "Requirements", validators=[DataRequired(), Length(min=3, max=500)]
    )
    service = QuerySelectField(
        query_factory=service_query, allow_blank=False, get_label="name"
    )
    submit = SubmitField("Order")


class AssignDevsToOrderForm(FlaskForm):
    developers = MultiCheckboxField("Developers", coerce=int)
    submit = SubmitField("Assign Selected")

    def validate_assignment(self, developers):
        for d in developers:
            if Developer.is_developer_available(d.id) == False:
                raise ValidationError(
                    "One of the developers cannot be assigned to the order. They have either already been assigned to the order, or are too busy."
                )

application/main/routes.py
from flask import render_template, request, redirect, url_for, Blueprint
from flask_login import current_user

main = Blueprint('main', __name__)

@main.route("/")
def home():
    if current_user.is_authenticated:
        if current_user.role.name == 'ADMIN':
          return redirect(url_for("accounts.dashboard"))
        return redirect(url_for("accounts.account"))
    return render_template("index.html")

application/orders/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from application import db
from application.orders.models import Order
from application.auth.models import Account
from application.orders.forms import OrderForm, AssignDevsToOrderForm
from application.auth import login_required
from application.services.models import Service
from application.developers.models import Developer

orders = Blueprint("orders", __name__)


def get_service(name):
    print(name)
    print(Service.query.filter_by(name=name).first())
    return Service.query.filter_by(name=name).first().id


@orders.route("/orders/new", methods=["GET", "POST"])
@login_required
def new_order():
    form = OrderForm()
    # services = Service.query.all()
    if form.validate_on_submit():
        print(form.service.data)
        order = Order(
            title=form.title.data,
            requirements=form.requirements.data,
            account_id=current_user.id,
            service_id=form.service.data.id,
            complete=False,
        )
        db.session.add(order)
        db.session.commit()
        flash("Your order has been created!", "success")
        return redirect(url_for("orders.client_orders", username=current_user.username))
    return render_template(
        "client/create_order.html", form=form, legend="New Order", title="New Order"
    )


@orders.route("/account/<string:username>")
@login_required
def client_orders(username):
    page = request.args.get("page", 1, type=int)
    client = Account.query.filter_by(username=username).first_or_404()
    orders = (
        Order.query.filter_by(account=client)
        .order_by(Order.date_created.desc())
        .paginate(page=page, per_page=5)
    )
    return render_template("client/client_orders.html", orders=orders, client=client)


@orders.route("/order/<int:order_id>")
@login_required
def order(order_id):
    order = Order.query.get_or_404(order_id)
    return render_template("client/order.html", title=order.title, order=order)


@orders.route("/order/<int:order_id>/update", methods=["GET", "POST"])
@login_required
def update_order(order_id):
    order = Order.query.get_or_404(order_id)
    if order.account != current_user:
        abort(403)
    form = OrderForm()
    if form.validate_on_submit():
        order.title = form.title.data
        order.requirements = form.requirements.data
        db.session.commit()
        flash("Your order has been updated!", "success")
        return redirect(url_for("orders.order", order_id=order.id))
    elif request.method == "GET":
        form.title.data = order.title
        form.requirements.data = order.requirements
    return render_template(
        "client/create_order.html",
        title="Update Order",
        form=form,
        legend="Update Order",
    )


@orders.route("/order/<int:order_id>/delete", methods=["POST"])
@login_required
def delete_order(order_id):
    order = Order.query.get_or_404(order_id)
    if order.account != current_user:
        abort(403)
    db.session.delete(order)
    db.session.commit()
    flash("Your order has been deleted!", "success")
    return redirect(url_for("orders.client_orders", username=current_user.username))


@orders.route("/admin/agency_orders", methods=["GET"])
@login_required(role="ADMIN")
def agency_orders():
    orders = Order.query.all()
    print(orders)
    for order in orders:
        print(order.account)
    return render_template(
        "admin/agency_orders.html", title="All orders", orders=orders
    )


@orders.route("/admin/order/<int:order_id>", methods=["GET", "POST"])
@login_required(role="ADMIN")
def admin_order(order_id):
    order = Order.query.get_or_404(order_id)
    developers_available = Developer.find_developers_with_skills_and_availability(
        order.service_id
    )
    

    
    form = AssignDevsToOrderForm()

    form.developers.choices = [
        (d.id, d.name)
        for d in Developer.query.all()
        if d.name in developers_available
        # and (Developer.is_developer_already_assigned(order_id, d.id) == True)
    ]



    if form.validate_on_submit():
        developer_record = Developer.query.all()
        # need a list to hold our choices
        assigned = []
        # looping through the choices, we check the choice ID against what was passed in the form
        for developer in developer_record:
            # when we find a match, we then append the object to our list
            if developer.id in form.developers.data:
                assigned.append(developer)
        order.developers = assigned
        db.session.add(order)
        db.session.commit()
    return render_template(
        "admin/order.html", title=order.title, order=order, form=form,
    )


@orders.route("/admin/order/<int:order_id>/mark_done", methods=["POST"])
@login_required(role="ADMIN")
def mark_done(order_id):
    order = Order.query.get_or_404(order_id)
    order.complete = True
    db.session.add(order)
    db.session.commit()
    flash("The order was marked as complete.", "success")
    return render_template("admin/order.html", title=order.title, order=order)

application/templates/client/account.html
{% extends "client/layout.html" %} {% block content %}
<div class="mx-auto w-50">
  <h1 class="mt-5 text-center">Welcome {{ name }}!</h1>
  <div class="d-flex flex-column">
    <div>
      <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Account Info</legend>
          <div class="form-group">
            {{ form.username.label(class="form-control-label") }} {% if
            form.username.errors %} {{ form.username(class="form-control
            form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.email.label(class="form-control-label") }} {% if
            form.email.errors %} {{ form.email(class="form-control
            form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.email(class="form-control form-control-lg") }} {%
            endif %}
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
      </form>
      <form
        method="POST"
        action=""
        enctype="multipart/form-data"
        onSubmit="return confirm('Are you sure you wish to delete?');"
      >
        {{ delete_form.hidden_tag() }}
        <div class="form-group red">
          {{ delete_form.delete(class="btn bg-danger") }}
        </div>
      </form>
    </div>
    <br />
    <div class="mb-5">
      <legend class="border-bottom mb-4">Orders</legend>
      <div class="d-flex p-2 mx-auto width: 300px">
        <a
          href="{{ url_for('orders.client_orders', username=current_user.username) }}"
          class="btn btn-primary mr-3"
          >View Orders</a
        >
        <a href="{{ url_for('orders.new_order', username=current_user.username) }}" class="btn btn-primary">Make Order</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

application/templates/client/admin.html
{% extends "client/layout.html" %} {% block content %}
<div class="container">
  <h1>Login with the following credentials to use admin functionality:</h1>
  <table class="table mt-5">
    <tr>
      <th>Username</th>
      <th>Password</th>
    </tr>
    <tr>
      <td class="font-weight-bold">admin</td>
      <td class="font-weight-bold">password</td>
    </tr>
  </table>
  <a href="{{ url_for('accounts.login') }}" class="btn btn-primary mr-3"
    >Log in</a
  >
</div>
{% endblock content%}

application/templates/client/client_orders.html
{% extends "client/layout.html" %} {% block content %}
<div class="container">
  <h1 class="mb-3">Orders by you ({{ client.username }}) [{{ orders.total }}]</h1>
  {% if orders.total == 0 %}
  <a
    href="{{ url_for('orders.new_order', username=current_user.username) }}"
    class="btn btn-primary"
    >Make Order</a
  >
  {% endif %}
  <ol class="list-group">
    {% for order in orders.items %}
    <li class="list-group-item">
      <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <p class="text-muted">
              Order made: {{ order.date_created.strftime('%Y-%m-%d') }}
            </p>
          </div>
          <h3>
            <a
              class="text-info""
              href="{{ url_for('orders.order', order_id=order.id) }}"
              >{{ order.title }}</a
            >
          </h3>
        </div>
      </article>
    </li>
    {% endfor %}
  </ol>
</div>

{% endblock content %}

application/templates/client/create_order.html
{% extends "client/layout.html" %} {% block content %}
<div class="container">
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ legend }}</legend>
        <div class="form-group">
          {{ form.title.label(class="form-control-label") }} {% if
          form.title.errors %} {{ form.title(class="form-control form-control-lg
          is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.title.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.title(class="form-control form-control-lg") }} {%
          endif %}
        </div>
        <div class="form-group">
          {{ form.service.label(class="form-control-label") }} {% if
          form.service.errors %} {{ form.service(class="form-control
          form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.service.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.service(class="form-control form-control-lg") }} {%
          endif %}
        </div>
        <div class="form-group">
          {{ form.requirements.label(class="form-control-label") }} {% if
          form.requirements.errors %} {{ form.requirements(class="form-control
          form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.requirements.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.requirements(class="form-control form-control-lg")
          }} {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
</div>
{% endblock content %}

application/templates/client/layout.html
<!DOCTYPE html>
<html>
  <head>
    <script src={{ url_for('static', filename='util.js') }}></script>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href={{ url_for('static', filename='style.css') }} />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap"
      rel="stylesheet"
    />

    {% if title %}
    <title>Dev Services - {{ title }}</title>
    {% else %}
    <title>Dev Services</title>
    {% endif %}
  </head>

  <body>
    <header>
      <a href="{{ url_for('main.home') }}" class="logo__link">
        <img
          src={{ url_for('static', filename='images/logo.svg') }}
          class="logo"
          alt="devServices logo"
        />
      </a>
      <nav class="nav__links">
        <ul>
          {% if current_user.is_authenticated %}
          <li><a href={{ url_for('orders.new_order') }}>New Order</a></li>
          <li><a href={{ url_for('accounts.account') }}>Account</a></li>
          <li><a href={{ url_for('accounts.logout') }}>Logout</a></li>
          {% else %}
          <li><a href={{ url_for('accounts.register') }}>Register</a></li>
          <li><a href={{ url_for('accounts.login') }}>Login</a></li>
          <li><a href={{ url_for('accounts.admin_credentials') }}>Admin</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
        <div>
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {% block content %} {% endblock %}
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

application/templates/client/login.html
{% extends "client/layout.html" %} {% block content %}
<div class="container">
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Log In</legend>
        <div class="form-group">
          {{ form.username.label(class="form-control-label") }} {% if
          form.username.errors %} {{ form.username(class="form-control
          form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-control-label") }} {% if
          form.password.errors %} {{ form.password(class="form-control
          form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-check">
          {{ form.remember(class="form-check-input") }} {{
          form.remember.label(class="form-check-label") }}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
      <small class="text-muted ml-2">
        <a href="#">Forgot Password?</a>
      </small>
    </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
      Need An Account?
      <a class="ml-2" href="{{ url_for('accounts.register') }}">Sign Up Now</a>
    </small>
  </div>
</div>
{% endblock content %}

application/templates/client/order.html
{% extends "client/layout.html" %} {% block content %}
<div class="container">
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        {% if order.account == current_user %}
        <table class="table mt-5">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Order Title</th>
              <th scope="col">Ordered</th>
              <th scope="col">Service</th>
              <th scope="col">Status</th>
            </tr>
          </thead>
          <tr>
            <th>{{ order.title }}</th>
            <th>{{ order.date_created.strftime('%Y-%m-%d') }}</th>
            <th>{{ order.service.name}}</th>
            {% if order.complete == True %}
            <th>Complete ✅</th>
            {% else %}
            <th>Received 🚧</th>
            {% endif %}
          </tr>
        </table>
        <div class="d-flex flex-column">
          <div class="d-flex">
            <a
              class="btn btn-secondary btn-sm mt-1 mb-1"
              href="{{ url_for('orders.update_order', order_id=order.id) }}"
              >Update</a
            >
            <button
              type="button"
              class="btn btn-danger btn-sm m-1"
              data-toggle="modal"
              data-target="#deleteModal"
            >
              Cancel
            </button>
          </div>
        </div>
        {% endif %} 
        
        {% if order.complete == False and order.developers %}
        <h2 class="pt-4">
          The Engineers working on your order:
        </h2>

        {% for developer in order.developers%}

        <div class="card px-4  m-3">
          <div class="card-body d-flex justify-content-between">
            <div class="card-title">{{developer.name}}</div>
            <div class="d-flex flex-end">
              <div class="card-subtitle mr-3">{{developer.experience()}}</div>
              <div class="card-subtitle block px-2">
                {{developer.costInEuros()}}
              </div>
          </div>
        </div>
        </div>
        {%endfor%} {%endif%}
  </article>
  <!-- Modal -->
  <div
    class="modal fade"
    id="deleteModal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="deleteModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Cancel Order?</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-secondary btn-sm"
            data-dismiss="modal"
          >
            Close
          </button>
          <form
            action="{{ url_for('orders.delete_order', order_id=order.id) }}"
            method="POST"
          >
            <input
              class="btn btn-danger btn-sm w-100"
              type="submit"
              value="Cancel"
            />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

application/templates/client/register.html
{% extends "client/layout.html" %} {% block content %}

<div class="container">
  <div class="content-section">
    <form method="POST" action="">
      <!-- accessing form instance
          hidden tag adds CORS token
      -->
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Work With Us</legend>
        <div class="form-group">
          {{ form.name.label(class="form-control-label") }} {% if
          form.name.errors %} {{ form.name(class="form-control form-control-lg
          is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.name.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.name(class="form-control form-control-lg") }} {%
          endif %}
        </div>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }} {% if
          form.email.errors %} {{ form.email(class="form-control form-control-lg
          is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.email(class="form-control form-control-lg") }} {%
          endif %}
        </div>
        <div class="form-group">
          {{ form.username.label(class="form-control-label") }} {% if
          form.username.errors %} {{ form.username(class="form-control
          form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-control-label") }} {% if
          form.password.errors %} {{ form.password(class="form-control
          form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.confirm_password.label(class="form-control-label") }} {% if
          form.confirm_password.errors %} {{
          form.confirm_password(class="form-control form-control-lg is-invalid")
          }}
          <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.confirm_password(class="form-control
          form-control-lg") }} {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
      Already Have An Account?
      <a class="ml-2" href="{{ url_for('accounts.login') }}">Sign In</a>
    </small>
  </div>
</div>
{% endblock content %}

application/templates/client/success.html
{% extends "client/layout.html" %} {% block content %}
<div class="container">
  <img src="../static/logo.png" alt="" class="logo" />
  <h1>Thank you for choosing us!</h1>
  <h2>Our 10x engineers will deliver your service swiftly and in style!</h2>
</div>
</br>
<div class="container">
  <h1>View your orders here:</h1>
  <a href="/orders">Orders</>
</div>
{% endblock content%}